"""Add new fields to doctor model

Revision ID: 3f82cdaea5d8
Revises: b247a1fc055d
Create Date: 2025-11-06 19:37:34.312919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f82cdaea5d8'
down_revision = 'b247a1fc055d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qualifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('availability')
        batch_op.drop_column('bio')
        batch_op.drop_column('qualifications')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
